FROM balenalib/armv7hf-debian as base_os
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-key adv --recv-key --keyserver keyserver.ubuntu.com C969F07840C430F5 || \
    apt-key adv --recv-key --keyserver pool.sks-keyservers.net C969F07840C430F5 || \
    apt-key adv --recv-key --keyserver pgp.mit.edu C969F07840C430F5
RUN echo 'deb http://repo.feed.flightradar24.com flightradar24 raspberrypi-stable' >> /etc/apt/sources.list

RUN apt-get update && apt-get install -y wget nano systemctl fr24feed

WORKDIR /opt/
COPY start.sh /opt/start.sh

CMD ./start.sh
